font_family monospace

cursor_blink_interval 0
cursor_shape block
shell_integration no-cursor

scrollback_lines -1
scrollback_pager "${HOME}"/.config/kitty/pager.sh INPUT_LINE_NUMBER CURSOR_LINE CURSOR_COLUMN

enable_audio_bell no
remember_window_size no
close_on_child_death yes
confirm_os_window_close 0

paste_actions replace-dangerous-control-codes

hide_window_decorations titlebar-and-corners
