[Service]
# $min_bat_perc instead of ${min_bat_perc} to prevent systemd expansion
ExecCondition=/bin/sh -c '\
if grep -q 1 /sys/class/power_supply/*/online 2>/dev/null; then \
  true; \
elif ! ls /sys/class/power_supply/BAT*/capacity > /dev/null 2>&1; then \
  true; \
else \
  min_bat_perc="$(cat /sys/class/power_supply/BAT*/capacity | sort -n | head -n1)"; \
  [ "$min_bat_perc" -ge 40 ]; \
fi'
