[keyboard]
bindings = [
  {key="h", mods="Control|Shift", mode="~Search", action="ToggleViMode"},
  {key="q", mode="Vi|~Search", action="ToggleViMode"},
  {key="q", mode="Vi|~Search", action="ScrollToBottom"},
]

[general]
import = [
  "theme.toml"
]

[font]
normal = {family="JetBrains Mono", style="Regular"}
