[tool]
[tool.ruff]
line-length = 88
extend-include = ["*.ipynb"]

[tool.ruff.lint]
extend-select = [
    "B", "C", "E", "F", "I", "RUF", "W"
]
ignore = [
    "E501", "RUF005"
]

[tool.ruff.lint.mccabe]
max-complexity = 18

[tool.ruff.lint.flake8-annotations]
suppress-none-returning = true
