name: sanitize_synced_files

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dependencies
      run: |
        sudo apt-get update --yes
        sudo apt-get install --yes --no-install-recommends git jq moreutils neovim parallel patch python3-pip shellcheck shfmt
        python3 -m pip install --upgrade --user ruff
    - uses: actions/checkout@v4
    - name: Sanitize
      run: |
        cp --recursive ./. ~/
        cd ~
        bash -c "source .profile && sanitize_synced_files.sh"
        git diff --exit-code
