name: test

on: [push]

jobs:
  test_build_and_sanitize:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/public' || github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        docker build --tag test:local --file ./.config/docker/test.dockerfile .
    - name: Sanitize
      run: |
        docker run test:local
