name: test

on: [push]

jobs:
  test_build_and_sanitize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        docker build --tag my_base:local --file ./.config/docker/my_base.dockerfile .
    - name: Sanitize
      run: |
        docker build --tag test:local --file ./.config/docker/test.dockerfile .
        docker run --volume=/var/run/docker.sock:/var/run/docker.sock test:local
